version: '2'

services:
    jenkins:
        build: .
        volumes:
            - "${HOME}/docker-volume/jenkins:/root/.jenkins"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        ports:
            - "8080:8080"
