version: '2'

services:
    jenkins:
        image: u6kapps/jenkins
        volumes:
            - "${DOCKER_VOLUMES}/jenkins:/root/.jenkins"
            - "/var/run/docker.sock:/var/run/docker.sock"
        environment:
            - "VIRTUAL_HOST=jenkins.u6k.me"
            - "VIRTUAL_PORT=8080"
            - "LETSENCRYPT_HOST=jenkins.u6k.me"
            - "LETSENCRYPT_EMAIL=u6k.apps@gmail.com"
        restart: always

networks:
    default:
        external:
            name: nginxproxy_default
